language: node_js
dist: bionic

sudo: false

cache:
  apt: true
  directories:
    - node_modules

# track upstream node_js matrix:
# - https://github.com/hexojs/hexo/blob/master/.travis.yml
# - https://github.com/sass/node-sass/blob/master/.travis.yml
node_js:
  - "16"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8

# https://github.com/sass/node-sass/blob/0c31dc2/.travis.yml#L73-L88
before_install:
  - npm config set python `which python3`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
        export CC="gcc-8";
        export CXX="g++-8";
        export LINK="gcc-8";
        export LINKXX="g++-8";
    fi

script:
  - npm run lint
  - npm run test-cov

after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
